### ISSUE TITLE
Bug with "-passthru=--fork=2" again (CORE ONLY)

### ISSUE THREAD

**Issue by frank-dittrich** [openwall/john-tests#40] opened 2015-02-02 21:05 UTC
```
(master)test $ ./jtrts.pl -type full "-passthru=--fork=2" -q
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0.2-jumbo-1-bleeding_omp_asAN [linux-gnu 64-bit AVX-autoconf]
--------------------------------------------------------------------------------
.pot CHK:dynamic_0                guesses: 1500 -show=1502 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1495 val-pwd)
.pot CHK:dynamic_0-raw            guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1491 val-pwd)
.pot CHK:dynamic_1                guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1491 val-pwd)
.pot CHK:dynamic_2                guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1493 val-pwd)
.pot CHK:dynamic_2-raw            guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1497 val-pwd)
.pot CHK:dynamic_3                guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1497 val-pwd)
.pot CHK:dynamic_3-raw            guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1491 val-pwd)
.pot CHK:dynamic_4                guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1489 val-pwd)
.pot CHK:dynamic_5                guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1490 val-pwd)
.pot CHK:dynamic_6                guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1489 val-pwd)
.pot CHK:dynamic_6-1salt          guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1495 val-pwd)
.pot CHK:dynamic_8                guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1491 val-pwd)
^C
```

etc

**Comment by jfoug** [comment] 2015-02-02 23:07
Running with -v -v, I saw this:

```
Execute john: /JtR/bleed/run/john -show    -pot=./tst.pot dynamic_1_new_tst.in -form=dynamic_1 2>&1

d_show_line2 = 
923 password hashes cracked, 577 left
4 invalid passwords
920 valid passwords
```

So, it appears there were 4 passwords that were not 'right'.  I will spend some more time digging in.

**Comment by jfoug** [comment] 2015-02-03 12:38
This is an issue with john and fork.

Here is some example screen output:

```
inkjet__9        (inkjet__9)
trustno1__4      (trustno1__4)
Swordfish__11    (S�imiey__4        (�imiey__4)
late&*ni��t__1   (late&*ni��t__1)
!!!!!!!!!__5     (!!!!!!!!!__5)
bartlby__15      (bartlby__15)
```

```
flasjkdfw__9     (flasjkdfw__9)
Bert&Ernie__4    (Bert&Ernie__4)
late*ni�h�       (late*ni�h�)
�tart123__4  sfga__3)
PIII__7          (PIII__7)
t00nv1ll3__7     (t00nv1ll3__7)
gobble__7        (gobble__7)
```

```
Skipping and& Dipping (Skipping and& Dipping)
1                (1)
BBSPw__2         (BBSPw__2)
Dragonquest__10  (Dragonquest__10    (�tart123__4)
dffffffffffff__7 (dffffffffffff__7)
pa�sw�rd1__�     (pa�sw�rd1__�)
ttttttt�ttt__5   (ttttttt�ttt__5)
hello__16        (hello__16)
```

What is happening is there is multi process interference.  Both processes are writing to screen, and or output files at same time.

I uncommented the FAILED line within pot_match_pass sub, and here is what I see:

```
FAILED line = Swordfish__11    (S�imiey__4        (�imiey__4)
FAILED line = hhello__12       (hhelwordfish__11)
FAILED line = !!!!!!!!!__11    (!!!!!lo__12)
FAILED line = password1__18    (password1__18!!!!__11)
FAILED line = as�fasfga__3     (as�fak__11)
FAILED line = Dragonquest__10  (Dragonquest__10    (�tart123__4)
FAILED line = nripper__13   (johnripper__13)
FAILED line = Will run 2 OpenMP threads per process (4 total across 2 processes)
FAILED line = Node numbers 1-2 of 2 (fork)
```

NOTE, the last to 'failures' will have to be accounted for, they are not failures, just lines that happen to 'match' the check-for criteria.  But the other lines you can see are 'chopped' up between 2 processes fighting with each other to write to the screen.

As long as jtr is not outputting to screen properly during -fork, then the TS will not succeed.

**Comment by jfoug** [comment] 2015-02-03 12:45
Just ran after muting the last 2 lines mentioned above that were spurious, and I have this:

```
FAILED line = good to KN0W__11 (good to KN0W__11)Wellington__13   (Wellington__13)
FAILED line = late&*night__14  (latesword1__5     (Password1__5)
FAILED line = Dragonquest__16  (Dragonquest__16&*night__14)
FAILED line = boneheadded__11  (bonehead3__15    (t00nv1ll3__15)
FAILED line = t00naracters__17   (characters__17)
FAILED line = v1ll3__4     (t00nv1ll3__4)

Execute john: /JtR/bleed/run/john -show    -pot=./tst.pot dynamic_1_tst.in -form=dynamic_1 2>&1

d_show_line2 = 
1500 password hashes cracked, 0 left
6 invalid passwords
1491 valid passwords

.pot CHK:dynamic_1                guesses: 1500 -show=1500 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1491 val-pwd)
Exiting on error. The .pot file ./tst.pot continas the found data
The command used to run this test was:
```

Note, even though jtr listed 1500 cracked (which there were), there were 6 invalid passwords, and 1491 that were seen. That means there were 3 lines that did not 'meet' the this is a password criteria.  If you look in the prior post of this thread, to the 2nd block I cut out from the output, you see a line that does not match password found criteria.  A password found must be of this format:

pass  (pass)

That line does not have a '(' character  That is why that line totally fails to be counted as anything.

But JtRts is working as it should.  JtR is not.

**Comment by jfoug** [comment] 2015-02-03 13:03
https://github.com/magnumripper/JohnTheRipper/commit/e36f0258db3bfa7da7fd7998ad0790d256f89c72

This makes it better, but not fixed.

**Comment by jfoug** [comment] 2015-02-03 13:17
There are still fork failures.  I am not sure if they are caused by this recent fflush(stdout) change, but do not see how.  This appears to be a true short run. The -show line comes from the .pot file:

```
form=dynamic_2                    guesses:  920 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_2                guesses:  920 0:00:00:00 DONE  [PASSED] (920 val-pwd)

form=dynamic_2-raw                guesses: 1500 -show=1327 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
.pot CHK:dynamic_2-raw            guesses: 1327 -show=1327 0:00:00:00 DONE : Expected count(s) (1500)  [!!!FAILED!!!]  (1327 val-pwd)

form=dynamic_3                    guesses: 1500 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_3                guesses: 1500 0:00:00:00 DONE  [PASSED] (1500 val-pwd)
```

**Comment by jfoug** [comment] 2015-02-03 13:29
Ok, I started another run, using -stop command line, to stop it.  Here is what I found:

```
form=dynamic_23                   guesses:  920 0:00:00:00 DONE  [PASSED]
.pot CHK:dynamic_23               guesses:  920 0:00:00:00 DONE  [PASSED] (920 val-pwd)

form=dynamic_24                   guesses: 1500 -show=1192 0:00:00:02 DONE : Expected count(s) (1500)  [!!!FAILED!!!]
Exiting on error. The .pot file ./tst.pot continas the found data
The command used to run this test was:

/JtR/bleed/run/john -ses=./tst  --fork=2 -pot=./tst.pot dynamic_24_tst.in --wordlist=pw.dic

$ wc tst.pot
 1193  1296 88621 tst.pot
```

So for whatever reason, being run in -fork=2 only generated 1192 lines of output.

**Comment by jfoug** [comment] 2015-02-05 14:29
NOTE, this was from core. I was about ready to say I could not get it to fail, BUT now I am not sure.  THe problem is the pwdum_lm that does not show 986 guesses:

```
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0
--------------------------------------------------------------------------------
.pot CHK:lm                       guesses: 1500 -show=3000 0:00:00:00 100% : Expected count(s) (1500)  [!!!FAILED!!!]  (1493 val-pwd)
.pot CHK:pwdump_lm                guesses:  986 -show=2760 0:00:00:00 100% : Expected count(s) (986)  [!!!FAILED!!!]  (984 val-pwd)
Some tests had Errors. Performed 2 tests.  2 errors reprocessing the .POT files
Time used was 1 seconds
jimfougeron@jimfougeron-vb-14-04:/c/phpbb/johnripper/bleed-64/test$ ./jtrts.pl -b=/JtR/core/run -passthru=--fork=2 lm -q
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0
--------------------------------------------------------------------------------
.pot CHK:lm                       guesses: 1500 -show=3000 0:00:00:00 100% : Expected count(s) (1500)  [!!!FAILED!!!]  (1492 val-pwd)
.pot CHK:pwdump_lm                guesses:  986 -show=2760 0:00:00:00 100% : Expected count(s) (986)  [!!!FAILED!!!]  (979 val-pwd)
Some tests had Errors. Performed 2 tests.  2 errors reprocessing the .POT files
Time used was 1 seconds
jimfougeron@jimfougeron-vb-14-04:/c/phpbb/johnripper/bleed-64/test$ ./jtrts.pl -b=/JtR/core/run -passthru=--fork=2 lm -q
-------------------------------------------------------------------------------
- JtR-TestSuite (jtrts). Version 1.13, Dec 21, 2014.  By, Jim Fougeron & others
- Testing:  John the Ripper password cracker, version 1.8.0
--------------------------------------------------------------------------------
.pot CHK:lm                       guesses: 1500 -show=3000 0:00:00:00 100% : Expected count(s) (1500)  [!!!FAILED!!!]  (1494 val-pwd)
.pot CHK:pwdump_lm                guesses:  493 -show=2760 0:00:00:00 100% : Expected count(s) (986)  [!!!FAILED!!!]  (981 val-pwd)
Some tests had Errors. Performed 2 tests.  2 errors reprocessing the .POT files
Time used was 1 seconds
```

Now that I have seen this, I am going to dig further.

**Comment by frank-dittrich** [comment] 2015-02-05 14:56
So, may be this bug can only be triggered for very fast formats.
Would testing --format=dummy also trigger it?

**Comment by jfoug** [comment] 2015-02-05 15:12
The stdio can be triggered by any format. That is why you are seeing core fail on pretty much every stdout compare.  Yes, a faster format will have worse screen IO corruption.

At the current time, I can only point fingers at jumbo, for -fork causing .pot file corruption. I am unable to get core to corrupt the .pot file.

As for any other fileIO  (log file, session file(s) etc), I do not know how to go about detecting if there is multi-process corruption or not.  Until recently, we did not even see it in the .pot files, but I would bet it has been there a long time.

**Comment by jfoug** [comment] 2015-02-09 11:40
We do not have a 'core' issue type here, so I changed to core only on title.

This is fixed on jumbo.  The screen output is 'ok'.  We still 'do' have a few lines of output which we should flush (things like when a key is pressed and status shown, and the screen IO upon exit of program), but those changes are pretty much make a non-impact.  

It could be that all calls to printf/puts within john should look for if was are RUNNING in fork mode, and if so, flush.  That way, nothing worries about flush until we call john_fork (which flushes itself when still in only parent mode), and then as soon as we wait for all children and they are gone, we could clear the options.nodes (or whatever it is), so that we are now again out of fork mode, and not needing to call fflush any more.

What say others about that concept?    But in the long run, the same thing should happen to core.  garbled screen IO is a problem there also.  The TS certainly shows when it is not right. TS is not 100% sure that it is fully right, just that it is 'right enough' to pass TS.

**Comment by magnumripper** [comment] 2015-11-09 23:15
I accidently wrote this as a commit comment at first:

Why are we even parsing screen output here? We should definitely parse the log, if need be with LogCrackedPasswords = Y. We should only ever parse screen output when there's simply no choice.

**Comment by frank-dittrich** [comment] 2015-11-10 07:01
It it is CORE ONLY, LogCrackedPasswords = Y wouldn't help.

**Comment by magnumripper** [comment] 2015-11-10 07:36
Can't we set stdout to unbuffered, much like hot pipe within perl?

**Comment by frank-dittrich** [comment] 2015-11-10 08:04
I think this will have a performance impact.

**Comment by frank-dittrich** [comment] 2015-11-10 08:09
Stdout buffering had been discussed on john-dev, see this thread:
http://thread.gmane.org/gmane.comp.security.openwall.john.devel/11872/focus=11903

**Comment by frank-dittrich** [comment] 2015-11-10 08:14
Does the issue still exist? Didn't Solar's commit aba31bac3ba0a81da39d16b82e94874253e56dee change the stdout output to line-buffered?

**Comment by frank-dittrich** [comment] 2015-11-10 08:32
So far, I did not manage to reproduce the problem with latest john and jtrts.pl.

**Comment by magnumripper** [comment] 2015-11-10 19:08
I meant the TS would somehow force unbuffered stdout, but apparently that's not trivial. Also, you may be perfectly right about aba31ba.

**Comment by jfoug** [comment] 2016-03-28 05:39
c181906 'may' force unbuffered line oriented stdout, BUT I am not sure that a child process has to honor that.  The c startup code may undo this, and it certainly will be undone if stdio is used (fprintf type crap).

c181906 needs to be tested to see if core is still 'broken'

**Comment by solardiz** [comment] 2020-09-24 17:14
Per the comments, this issue appears to be fixed, only needing re-testing to make sure that is the case. I'll close it now. If anyone does re-test, please post a comment in here (even to the closed issue). If the issue is found still not fixed (or reintroduced) and you care, please feel free to reopen it.

**Closed by solardiz** 2020-09-24 17:14 UTC
Labels: bug
